{% set version = "0.2.0" %}
{% set sha256 = "ffc11de027ca65da12b0dbb434222ca871b68d6dab6386dbef3388293d1b28f9" %}

package:
  name: pyam
  version: {{ version }}

source:
  url: https://github.com/IAMconsortium/pyam/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - argparse
    - numpy
    - pandas >=0.21.0,!=0.24.0
    - pyyaml
    - xlrd
    - xlsxwriter
    - matplotlib
    - seaborn
    - six
    - geopandas <0.5.0
    - cartopy
    - gdal
    - fiona
    - requests

test:
  imports:
    - pyam

about:
  home: https://github.com/IAMconsortium/pyam
  license: Apache-2.0
  license_file: LICENSE
  summary: 'an open-source Python package for IAM scenario analysis and visualization https://software.ene.iiasa.ac.at/pyam/'

extra:
  recipe-maintainers:
    - gidden
