{% set version = "0.13.0" %}
{% set sha256 = "ae3e8877c0d759aa501376e140806d32937a94bcef5b1bb5d9cd52c28e451c77" %}

package:
  name: pyam
  version: {{ version }}

source:
  url: https://github.com/IAMconsortium/pyam/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - pandas
    - pyyaml
    - matplotlib-base
    - seaborn
    - six
    - requests
    - iam-units
    - xlrd
    - openpyxl
    - datapackage

test:
  imports:
    - pyam
  commands: python -c "import pyam; assert pyam.__version__ == '{{ version }}'"

about:
  home: https://pyam-iamc.readthedocs.io/
  license: Apache-2.0
  license_file: LICENSE
  summary: Analysis and visualization of integrated-assessment & macro-energy scenarios
  description: |
    The open-source Python package **pyam** provides a suite of tools and functions
    for analyzing and visualizing input data (i.e., assumptions/parametrization)
    and results (model output) of integrated-assessment models,
    macro-energy scenarios, energy systems analysis, and sectoral studies.

    **Key features**

    - Simple analysis of scenario timeseries data with an interface similar in feel & style
      to the widely used [pandas.DataFrame](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html)
    - Advanced visualization and plotting functions
      (see the [gallery](https://pyam-iamc.readthedocs.io/en/stable/gallery/index.html))
    - Scripted validation and processing of scenario data and results
  doc_url: https://pyam-iamc.readthedocs.io/
  dev_url: https://github.com/IAMconsortium/pyam

extra:
  recipe-maintainers:
    - gidden
    - danielhuppmann
