{% set version = "0.1.2" %}
{% set sha256 = "3e9f8efe2c5f6fc62b69fbc65fcc64f50e23b74819e102c3bc9a314e27e5c9b8" %}

package:
  name: pyam
  version: {{ version }}

source:
  url: https://github.com/IAMconsortium/pyam/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - numpy
    - pandas >=0.21.0
    - pyyaml
    - xlrd
    - xlsxwriter
    - matplotlib
    - seaborn
    - six
    - geopandas
    - cartopy
    - requests

test:
  imports:
    - pyam

about:
  home: https://github.com/IAMconsortium/pyam
  license: Apache-2.0
  license_file: LICENSE
  summary: 'an open-source Python package for IAM scenario analysis and visualization https://software.ene.iiasa.ac.at/pyam/'

extra:
  recipe-maintainers:
    - gidden
