{% set version = "0.2.0" %}

package:
  name: pyam
  version: {{ version }}

source:
  url: https://github.com/IAMconsortium/pyam/archive/v{{ version }}.tar.gz
  sha256: f7bfadd75bf4fd33bd20102d5dc5635e4a00976a2a866062f84498062f847e75

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - numpy
    - pandas
    - pyyaml
    - xlrd
    - xlsxwriter
    - matplotlib
    - seaborn
    - six
    - geopandas
    - cartopy
    - gdal
    - fiona
    - requests

test:
  imports:
    - pyam
  commands:
     python -c "import pyam; assert pyam.__version__ == '{{ version }}'"

about:
  home: https://github.com/IAMconsortium/pyam
  license: Apache-2.0
  license_file: LICENSE
  summary: 'an open-source Python package for IAM scenario analysis and visualization https://software.ene.iiasa.ac.at/pyam/'

extra:
  recipe-maintainers:
    - gidden
