{% set version = "1.3.0" %}
{% set sha256 = "47839a29932623ff100d5fb367c9ea5bc3db6758dda11980397a1c33da83ea12" %}

package:
  name: pyam
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyam-iamc/pyam-iamc-{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools-scm
  run:
    - python >=3.7
    - iam-units >=2020.4.21
    - datapackage
    - numpy >=1.19.0
    - requests
    - openpyxl
    - pandas >=1.1.1
    - pyyaml
    - matplotlib-base >=3.2.0
    - seaborn
    - six
    - xlrd >=2.0
    - pint >=0.11
    - setuptools_scm
    - importlib_metadata

test:
  imports:
    - pyam
  commands: python -c "import pyam; assert pyam.__version__ == '{{ version }}'"

about:
  home: https://pyam-iamc.readthedocs.io/
  license: Apache-2.0
  license_file: LICENSE
  summary: Analysis and visualization of integrated-assessment & macro-energy scenarios
  description: |
    The open-source Python package **pyam** provides a suite of tools and functions
    for analyzing and visualizing input data (i.e., assumptions/parametrization)
    and results (model output) of integrated-assessment models,
    macro-energy scenarios, energy systems analysis, and sectoral studies.

    **Key features**

    - Simple analysis of scenario timeseries data with an interface similar in feel & style
      to the widely used [pandas.DataFrame](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html)
    - Advanced visualization and plotting functions
      (see the [gallery](https://pyam-iamc.readthedocs.io/en/stable/gallery/index.html))
    - Scripted validation and processing of scenario data and results
  doc_url: https://pyam-iamc.readthedocs.io/
  dev_url: https://github.com/IAMconsortium/pyam

extra:
  recipe-maintainers:
    - gidden
    - danielhuppmann
