{% set version = "0.3.0" %}
{% set sha256 = "646e417fd961a84dcdb004e5dd02b134d090ec03e9b25407f064d779e888c9e3" %}

package:
  name: pyam
  version: {{ version }}

source:
  url: https://github.com/IAMconsortium/pyam/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - numpy
    - pandas
    - pyyaml
    - xlrd
    - xlsxwriter
    - matplotlib
    - seaborn
    - six
    - geopandas
    - cartopy
    - gdal
    - fiona
    - requests

test:
  imports:
    - pyam
  commands:
     python -c "import pyam; assert pyam.__version__ == '{{ version }}'"

about:
  home: https://github.com/IAMconsortium/pyam
  license: Apache-2.0
  license_file: LICENSE
  summary: 'an open-source Python package for IAM scenario analysis and visualization https://pyam-iamc.readthedocs.io'

extra:
  recipe-maintainers:
    - gidden
    - danielhuppmann
