{% set version = "0.5.0" %}
{% set sha256 = "6a19f8d80865c919d20c7fe674c36a4dd54eac9aad51777d3c2c5a4c6dc63997" %}

package:
  name: pyam
  version: {{ version }}

source:
  url: https://github.com/IAMconsortium/pyam/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - numpy
    - pandas
    - pyyaml
    - xlrd
    - xlsxwriter
    - matplotlib
    - seaborn
    - six
    - requests

test:
  imports:
    - pyam
  commands: python -c "import pyam; assert pyam.__version__ == '{{ version }}'"

about:
  home: https://pyam-iamc.readthedocs.io/
  license: Apache-2.0
  license_file: LICENSE
  summary: a Python package for integrated-assessment scenario analysis and visualization
  description: |
    The open-source Python package `pyam` provides a suite of tools and
    functions for analyzing and visualizing input data
    (i.e., assumptions/parametrization) and results (model output) of
    integrated-assessment scenarios.

    # Key features:
    - Simple analysis of timeseries data in the IAMC format with an interface
      similar in feel and style to the widely used pandas.DataFrame
    - Advanced visualization and plotting function
    - Diagnostic checks for scripted validation of scenario data and results
  doc_url: https://pyam-iamc.readthedocs.io/
  dev_url: https://github.com/IAMconsortium/pyam

extra:
  recipe-maintainers:
    - gidden
    - danielhuppmann
