{% set version = "0.1.1" %}
{% set sha256 = "f797d97e820dffcdeb7d38a3fb87df0792b197c6caae6117a4898d9aeffd0ec4" %}

package:
  name: pyam
  version: {{ version }}

source:
  url: https://github.com/IAMconsortium/pyam/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - numpy
    - pandas >=0.21.0
    - pyyaml
    - xlrd
    - xlsxwriter
    - matplotlib
    - seaborn
    - six
    - geopandas
    - cartopy

test:
  imports:
    - pyam

about:
  home: https://github.com/IAMconsortium/pyam
  license: Apache-2.0
  license_file: LICENSE
  summary: 'an open-source Python package for IAM scenario analysis and visualization https://software.ene.iiasa.ac.at/pyam/'

extra:
  recipe-maintainers:
    - gidden
