travis:
  secure:
    BINSTAR_TOKEN: tqaGbNmjDkZttmCg/KFaHYTBUdRsALNHlJ49Tf2vv1k8GzQn8gnOrwJGyTLpl3oAp56bSkJ+BlqaWahJ0sZYTkiToNiMaLgf8VdYIqOEZWjoz+sKeTJrl2WTOFCREXzKJ7EVbRz7OtTSDhFITQG6RIJwr9RTDgTyU/iu1k4mQRily357Hd9UKAupY/moHZG+f/zSXgKJWoVgkWQCUiITbNv2zOIK2lh8cyMdEY/YastPaVfoklbmWQczuqemHKnZTV8ye4QNgCvrkcOwLqYbNaZwIamY8CSOw11faOi/FEb7mBgoH6P+4gAHSS0+FYdW0T5S03X+GN/k7YiV3QU9q1rKu1gbw2jNXtGKu32zQHG6lyzfteWxUM8nmjqpgk+nj0zsvHLJMhtZ3GfQ2cVwUpU6Ao3E9SP9068Tq++AWatDrgmvxz5keLiN1N9r8OO9AmZpIArn6DBTOldI+4M3RCZ3xGXvKZnTUZU+gN63w21uJ38JfbzmQzSV/7RsNnKc4pIF/Mxo5O7uBQZsOCIjIqkjtBQvSyVqdpS9F1TpcAA156XMuKKtqY7Dyut1e03OUzCz+3cDO3V3QBcv3zaIfeXLez+TgdrHxMwEPloYRw7b8Aq2ofpUj2Lc6OwLRzN7Hm71jZutMLtfPrS6Ff8jo3QrglEqC+AIHQKB4nuf74g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
